title: International Conference on Supercomputing 2022
author: Jacqueline Bruen
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  
show_excerpts: true # set to false to remove excerpts on the homepage

